"""add image fields to mango product

Revision ID: e07fa93a1aaf
Revises: 0c5bf0829d50
Create Date: 2026-06-29 08:30:06.033270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e07fa93a1aaf'
down_revision: Union[str, Sequence[str], None] = '0c5bf0829d50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mango_products', sa.Column('image_public_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mango_products', 'image_public_id')
    # ### end Alembic commands ###
